export const userReducerConstant = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  STORE_LIST: 'STORE_LIST',
  LOGIN_USER: 'LOGIN_USER',
  CURRENT_STORE: 'CURRENT_STORE'
};

export const loaderReducerConstant = {
  TOGGLE_LOADER: 'TOGGLE_LOADER'
};

export const activeGarmentConstant = {
  ACTIVE_GARMENT_DATA: 'ACTIVE_GARMENT_DATA',
  ACTIVE_GARMENT_WITH_S3_STRUCTURE_DATA: 'ACTIVE_GARMENT_WITH_S3_STRUCTURE_DATA',
  GARMENT_STORE_NAME: 'GARMENT_STORE_NAME',
  ADVANCED_INPUTS: 'ADANCED_INPUTS',
  PRESETSLIST: 'PRESETSLIST'
};

export const snackBarReducerConstant = {
  SNACKBAR_SUCCESS: 'SNACKBAR_SUCCESS',
  SNACKBAR_FAILURE: 'SNACKBAR_FAILURE',
  SNACKBAR_CLEAR: 'SNACKBAR_CLEAR',
  PAGELOADER: 'PAGELOADER'

};
